[package]
name = "img-annotator"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.24"
egui = "0.24"
image = "0.24"
glob = "0.3"
anyhow = "1.0"
winapi = { version = "0.3.9", features = ["winuser", "windef"] }